<?php
/**
 * @var $jwt
 */
?>
<div class="content">
    <form id="form_login" method="post" action="/account/login">
        <input type="hidden" name="jwt" value="<?= $jwt ?>">
        <h1 class="mb-3">Se connecter</h1>
        <p class="form-text text-danger" id="unknown-field" aria-hidden="true"><strong>Identifiant ou mot de passe inconnu</strong></p>
        <?php
        if (isset($_SESSION["success-create"]) && $_SESSION["success-create"])
        {
                ?>
                <p class="form-text text-success"><strong>Votre compte a été correctement créé !</strong></p>
                <?php
            unset($_SESSION["success-create"]);
        }
        if (isset($_SESSION["login-error"]) && !empty($_SESSION["login-error"]))
        {
            ?>
            <p class="form-text text-danger"><strong><?= $_SESSION["login-error"]; ?></strong></p>
            <?php
            unset($_SESSION["login-error"]);
        }
        ?>
        <div class="row mb-3">
            <label for="login" class="form-label col mt-2">Identifiant</label>
            <input type="text" class="form-control col" id="login" name="login" value="<?php if(isset($_SESSION["lastUsername"])) echo $_SESSION["lastUsername"] ?>">
        </div>
        <div class="row mb-3">
            <label for="password" class="form-label col mt-2">Mot de passe</label>
            <input type="password" class="form-control col" id="password" name="password">
        </div>
        <div class="mb-3">
            <a href="/account/create" class="form-text">Pas de compte ? Créez-en un</a>
        </div>
        <button name="form-login-submitted" type="submit" class="btn btn-jct-orange" id="btn-connect">Se connecter</button>
    </form>
</div>