<div class="content">
    <form id="form_login" method="post" action="index.php?controller=account&action=doCreate">
        <input type="text" aria-hidden="true" name="jwt" value="<?= $jwt ?>">
        <h1 class="mb-3">Créer un compte</h1>
        <?php
        if (isset($_SESSION["error-create-token"]) && $_SESSION["error-create-token"])
        {
            ?>
            <p class="form-text text-danger"><strong>Une erreur est survenue, veuillez réessayer</strong></p>
            <?php
            unset($_SESSION["error-create-token"]);
        }
        if(isset($_SESSION["error-create"]))
        {
            foreach($_SESSION["error-create"] as $str)
            {
                ?>
                <p class="form-text text-danger" id="unknown-field"><strong><?=$str?></strong></p>
                <?php
            }
        unset($_SESSION["error-create"]);
        }
        ?>
        <p class="form-text text-danger" id="unknown-field"><strong></strong></p>
        <div class="mb-3">
            <a href="index.php?controller=account" class="form-text"><< Retour</a>
        </div>
        <div class="row mb-3">
            <label for="cLogin" class="form-label col mt-2">Identifiant</label>
            <input type="text" class="form-control col" id="cLogin" name="cLogin">
        </div>
        <div class="row mb-3">
            <label for="cPassword" class="form-label col mt-2">Mot de passe</label>
            <input type="password" class="form-control col" id="cPassword" name="cPassword">
        </div>
        <div class="row mb-3">
            <label for="cPasswordVerify" class="form-label col mt-2">Vérifier le mot de passe</label>
            <input type="password" class="form-control col" id="cPasswordVerify" name="cPasswordVerify">
        </div>
        <div class="row mb-3">
            <label for="cMail" class="form-label col mt-2">Adresse mail</label>
            <input type="text" class="form-control col" id="cMail" name="cMail">
        </div>
        <button name="form-create-account-submitted" type="submit" class="btn btn-jct-orange" id="btn-connect">Créer mon compte</button>
    </form>
</div>