<?php
// views/account/afficAccount.phtml

/**
 * @var Client $client
 */
?>
<div class="content">
    <div class="row mb-5">
        <div class="list-group list-group-flush col">
            <a href="/account/historique" class="list-group-item list-group-item-action text-blue">Historique des commandes</a>
            <a href="/account/logout" class="list-group-item list-group-item-action text-blue">Se déconnecter</a>
        </div>
        <div class="list-group list-group-flush col">
            <a href="/account/infos" class="list-group-item list-group-item-action text-blue">Modifier mes informations</a>
        </div>
    </div>
</div>