<?php
/**
 * @var $jwt
 */
?>
<div id="center_block">
    <form id="form_login" method="post" action="/account/login">
        <input type="hidden" name="jwt" value="<?= $jwt ?>">
        <h1 class="mb-3">Se connecter</h1>
        <?php
        //Messages de succès/d'erreur
        if (isset($_SESSION["create-success"]) && $_SESSION["create-success"])
        {
                ?>
                <p class="form-text text-success"><strong>Votre compte a été correctement créé !</strong></p>
                <?php
            unset($_SESSION["create-success"]);
        }
        if (isset($_SESSION["login-error"]) && !empty($_SESSION["login-error"]))
        {
            ?>
            <p class="form-text text-danger"><strong><?= $_SESSION["login-error"]; ?></strong></p>
            <?php
            unset($_SESSION["login-error"]);
        }
        ?>
        <div class="row mb-3">
            <label for="login" class="col-form-label col-lg-2">Identifiant</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="login" name="login"
                       value="<?php if(isset($_SESSION["lastUsername"])) echo $_SESSION["lastUsername"] ?>">
            </div>
        </div>
        <div class="row mb-3">
            <label for="password" class="col-form-label col-lg-2">Mot de passe</label>
            <div class="col-lg-10">
                <input type="password" class="form-control" id="password" name="password">
            </div>
        </div>
        <div class="mb-3">
            <a href="/account/create" class="form-text">Pas de compte ? Créez-en un</a>
        </div>
        <button name="form-login-submitted" type="submit" class="btn btn-jct-orange" id="btn-connect">Se connecter</button>
    </form>
</div>