<div id="main_affic">
    <h1>Mon panier</h1>
    <?php
    if (count($this->Panier()->Panier()) == 0) {
        echo "<p>Votre panier est vide</p>";
    } else {
        ?>
        <form method="post" action="/panier/update" id="update_panier">
            <table class="table table-striped table-borderless">
                <?php
                foreach ($this->Panier()->Panier() as $lignePanier) {
                    /** @var Produit $produit */
                    $produit = $lignePanier["produit"];
                    $qte = $lignePanier["qte"];
                    ?>
                    <tr>
                        <td style="width:calc(127px + 1rem);position:relative;">
                            <a href="/produit/<?php echo $produit->GetRefProduit() ?>">
                                <img src="/assets/<?php echo $produit->GetImgPath() ?>"
                                     alt="<?php echo $produit->GetRefProduit() ?>"
                                     style="max-width:127px;height:auto;">
                            </a>
                        </td>
                        <td>
                            <p class="fs-3 mb-1 fw-bold">
                                <a href="/produit/<?php echo $produit->GetRefProduit() ?>"
                                   class="text-decoration-none">
                                    <?php echo $produit->GetLibProduit() ?></a>
                            </p>
                            <div class="row align-items-center mb-1">
                                <div class="col-auto">
                                    <label for="qte" class="text-muted col-form-label">Qte :</label>
                                </div>
                                <div class="col-auto">
                                    <input min="0" name="panier[<?php echo $produit->GetRefProduit() ?>]" id="qte"
                                           class="form-control" type="number"
                                           value="<?php echo $qte ?>" max="<?php echo $produit->GetQteStock() ?>">
                                </div>
                            </div>
                            <?php
                            if($produit->GetQteStock() < $qte) {
                                ?>
                                <p class="text-danger">Il ne reste que <?php echo $produit->GetQteStock() ?> exemplaires en stock</p>
                                <?php
                            } else {
                                ?>
                                <p class="text-muted">Total produit :&nbsp;
                                    <span class="text-jct-orange"><?php echo number_format($produit->GetPrix() * $qte, 2) ?>&nbsp;€</span>
                                </p>
                                <?php
                            }
                            ?>
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </table>
            <h2 class="text-end">Total&nbsp;:&nbsp;<span class="text-jct-orange text-decoration-underline"><?php
                    echo $this->Panier()->PrixTotalFormatted() ?>&nbsp;€</span></h2>
            <button type="submit" class="btn btn-warning mt-3">Mettre à jour le panier</button>
        </form>
        <?php
    }
    ?>
    <a class="btn btn-success mt-3 <?php if($this->Panier()->PrixTotal() == 0) echo "disabled" ?>" href="/panier/infosCommande">Passer la commande</a>
</div>
