<?php
if (!isset($hasNav) || $hasNav == true) {
    $categs = CategorieManager::GetLesCategories();
    $user = $this->Request()->user();
    $panier = $this->Panier()->Panier();
    ?>
    <!--Main header-->
    <header id="main_header">
        <div id="header_left">
            <a id="header_title" href="/">
                Jean Casse-Tête
            </a>
            <?php
            $html = "";
            /**
             * @var $categ Categorie
             */
            foreach ($categs as $categ) {
                $html .=
                    "<a id=\"" . $categ->GetRef() . "\" class=\"header_item";
                if (isset($_GET["categorie"]) && !empty($_GET["categorie"]) && $_GET["categorie"] == $categ->GetRef())
                    $html .= " active";
                $html .=
                    "\" href=\"/categorie/" . $categ->GetRef() . "\">\n" .
                    $categ->GetLibelle() .
                    "</a>\n";
            }
            echo $html;
            ?>
        </div>
        <div id="header_right">
            <a data-bs-toggle="offcanvas" href="#offcanvasPanier" role="button" aria-controls="offcanvasPanier">
                <i class="fas fa-shopping-cart"></i> <?php echo $this->Panier()->QteTotale(); ?>
            </a>
            <a href="/account"><i class="fas fa-user"></i><span
                        id="accountMsg"><?php echo $user ? $user->GetLogin() : "Connectez-vous" ?></span>
            </a>
        </div>
    </header>

    <?php
    include VUES . "/header/afficPanierOffcanvas.phtml";

} else {
    ?>
    <!--Simple header (no nav)-->
    <header id="main_header">
        <div id="header_left" class="w-100">
            <a class="justify-content-center w-100" id="header_title" href="/">Jean Casse-Tête</a>
        </div>
    </header>
    <?php
}