<?php
/**
 * @var array $panier
 */
?>

<div class="offcanvas offcanvas-end" id="offcanvasPanier" tabindex="-1" aria-labelledby="offcanvasPanierLabel">
    <div class="offcanvas-header">
        <h1 class="offcanvas-title" id="offcanvasPanierLabel">Panier</h1>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body p-0">
        <?php
        if (count($panier) == 0) {
            echo "<div>Le panier est vide</div>";
        } else {
            ?>
            <table class="table table-striped table-borderless">
                <?php
                foreach ($panier as $lignePanier) {
                    /** @var Produit $produitPanier */
                    $produitPanier = $lignePanier["produit"];
                    $qte = $lignePanier["qte"];
                    ?>
                    <tr>
                        <td class="row_panier_image">
                            <img src="/assets/<?php echo $produitPanier->GetImgPath() ?>"
                                 alt="<?php echo $produitPanier->GetRefProduit() ?>">
                        </td>
                        <td>
                            <p class="fs-4 mb-1 fw-bold"><?php echo $produitPanier->GetLibProduit() ?></p>
                            <?php
                            $qteRestante = $produitPanier->GetQteStock() - $produitPanier->GetQteCommandee();
                            if($produitPanier->EstEnRupture()) {
                                ?>
                                <p class="text-danger">Rupture de stock</p>
                                <?php
                            } else if($qteRestante < $qte) {
                                ?>
                                <p class="text-danger">Il n'y a plus assez d'article en stock</p>
                                <?php
                            } else {
                                ?>
                                <p class="text-muted">Qté : <?php echo $qte ?>
                                    -
                                    <span class="text-jct-orange"><?php echo number_format($produitPanier->GetPrix() * $qte, 2) ?> €</span>
                                </p>
                                <?php
                            }
                            ?>
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </table>
            <div class="m-2">
                <p class="text-end text-muted fs-5 mb-2">Total : <span class="text-jct-orange"><?php echo $this->Panier()->PrixTotalFormatted() ?> €</span></p>
                <div class="text-center px-4">
                    <a class="btn btn-warning w-100 py-1 px-2" href="/panier">Accèder au panier</a>
                    <a class="btn btn-success mt-1 w-100 py-1 px-2 <?php if($this->Panier()->PrixTotal() == 0) echo "disabled" ?>" href="/panier/infosCommande">Passer la commande</a>
                </div>
            </div>
            <?php
        }
        ?>
    </div>
</div>