<?php
/**
 * @var array $sousCategs
 * @var array $produits
 */
?>
<div id="filters_panel">
    <form method="get">
        <div id="filters_header">
            <h2>Filtres</h2>
        </div>
        <div id="filters_content">
            <div class="accordion" id="filters_accordion">
                <?php
                include(ROOT . "/views/categorie/accordionTri.inc");
                if (count($sousCategs)) {
                    include($_SERVER["DOCUMENT_ROOT"] . "/views/categorie/accordionCateg.inc");
                }
                include(ROOT . "/views/categorie/accordionDifficulte.inc");
                ?>
            </div>
        </div>
        <div id="filters_button">
            <div>
                <button type="submit" class="btn btn-jct-orange">Filtrer</button>
            </div>
            <div class="mt-2">
                <a href="/categorie/<?php echo $this->Request()->get("categorie") ?>"
                   class="btn btn-grey">Effacer les filtres</a>
            </div>
        </div>
    </form>
</div>

<div class="liste_produits m-4">
    <?php
    foreach($produits as $produit)
    {
        include ROOT . "/views/produit/ficheProduit.inc";
    }
    ?>
</div>
